#sudo docker-compose up -d
#sudo docker-compose down
#sudo docker-compose ps
#docker stop docker_nodejs_1
#docker logs docker_nodejs_1
#docker exec -ti docker_php_1 /bin/bash

version: '3'

services:
    couchdb:
        image: couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpass
        ports:
            - 5984:5984
        volumes:
            - ./volumes/couchdb:/opt/couchdb/data
        restart: on-failure

        
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=adminpass
        ports:
            - 5432:5432
        volumes:
            - ./volumes/postgres:/docker-entrypoint-initdb.d
        restart: on-failure


    rabbitmq:
        image: rabbitmq:3
        hostname: my-rabbit
        ports:
            - 5672:5672
        restart: on-failure


    nodejs:
        image: node
        working_dir: /usr/src/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./nodejs:/usr/src/app/
        ports:
            - 3000:3000
        depends_on:
            - couchdb
            - rabbitmq
            - postgres
        command: "node totale.js"
        restart: on-failure
        

    php:
        build:
            context: ./php
        ports:
            - 9000:9000
        volumes:
            - ./nginx:/usr/share/nginx/html
            - ./volumes/PHP/php.ini:/usr/local/etc/php/php.ini
        #command: bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install pdo pdo_pgsql pgsql"
        restart: on-failure


    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/SSL:/etc/nginx/certs
        depends_on:
            - nodejs
            - php
        restart: on-failure
    
